apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ngrkgawz
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ngrkgawz:595432bb880a1faf7200163e94b8f46169b622f0@sha256:03cc366902dc7005a5fe8e81b17285fd7e77056c4b64a1f786f57b73c952f812
        name: container-image  
